### ISSUE TITLE
Настроить .gitignore

### ISSUE THREAD

**Issue by zarikadzer** [Advance-Technologies-Foundation/SetupDevEnv#7]
Настроить .gitignore

**Comment by egenov** [comment]
Вроде уже не актуально
https://github.com/Advance-Technologies-Foundation/SetupDevEnv/blob/master/.gitignore

**Comment by zarikadzer** [comment]
Суть в том, что в данный момент он настроен не правильно.

**Comment by egenov** [comment]
@zarikadzer так, а чего не хватает? Предлагаю просто по мере необходимости добавлять в него исключения, а не сразу на все случаи жизни

**Comment by zarikadzer** [comment]
Добавил, на все случаи:)

**Comment by egenov** [comment]
@zarikadzer  :)
